### ISSUE TITLE
TypeError when parsing cyclonedx-py json 

### ISSUE THREAD

**Issue by edmerrett** [madpah/vexy#10]
Hey,

I am using cyclonedx-bom - when passing the the output json file into vexy I get a type error.
`TypeError: __init__() got an unexpected keyword argument 'serial_number'`

Likely an issue with the imported library, however wanted to check if this was a known issue.

Running:

`cyclonedx-py -e -F | vexy -i cyclonedx.json -c VEXY_CONFIG -X`

Full error: 

```[DEBUG] - 2022-10-11 14:55:30.644179 - !!! DEBUG MODE ENABLED !!!
[DEBUG] - 2022-10-11 14:55:30.644228 - Parsed Arguments: Namespace(debug_enabled=True, input_source=<_io.TextIOWrapper name='cyclonedx.json' mode='r' encoding='UTF-8'>, output_file=True, output_file_overwrite=False, output_format='xml', output_schema_version='1.4', quiet_enabled=False, vexy_config=<_io.TextIOWrapper name='VEXY_CONFIG' mode='r' encoding='UTF-8'>)
Vexy is configured to use 1 data sources.
Parsing CycloneDX BOM for Components ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/Users/xx/xx/xx/xx/.venv/bin/vexy", line 10, in <module>
    sys.exit(main())
  File "/xx/xx/xx/xx/xx/.venv/lib/python3.8/site-packages/vexy/client.py", line 288, in main
    VexyCmd(args).execute()
  File "/xx/xx/xx/xx/xx/.venv/lib/python3.8/site-packages/vexy/client.py", line 158, in execute
    parser.parse_bom()
  File "/xx/xx/xx/xx/xx/.venv/lib/python3.8/site-packages/vexy/parser/cyclonedx.py", line 53, in parse_bom
    self.bom = Bom(serial_number=bom_data.get('serialNumber'), version=bom_data.get('version'))
TypeError: __init__() got an unexpected keyword argument 'serial_number'

**Comment by edmerrett** [comment]
I managed to get around this by updating some of the functions in the cyclonedx lib to expect `serial_number` and `version`

However vexy then goes and throws an error running OSV scanning as the cyclonedx SBOM generated using cyclonedx-py doesn't include a `vulnerabilities` key/value pair. Adding this in didn't work.

**Comment by madpah** [comment]
Hey @edmerrett - thanks for raising. I haven't had chance to work on `vexy` for a few months - but will get back to this over the festive break I hope!

**Comment by edmerrett** [comment]
Nice one @madpah 
Would love to support if there is a opportunity to contribute

**Comment by vjclions** [comment]
We run into same TypeError problem. Wondering if this problem has been fixed.

**Comment by northdpole** [comment]
same problem here, @madpah , vexy is a very useful tool, how can we help you maintain it?

**Comment by madpah** [comment]
Hey @northdpole @vjclions @edmerrett - do you have an example SBOM that you are supplying to `vexy` you can share?

**Comment by madpah** [comment]
Reproduced it @northdpole @vjclions @edmerrett - should have a fix shortly.

**Comment by madpah** [comment]
@edmerrett @northdpole @vjclions - I believe `vexy` `0.3.1` resolves this. Be aware it relies on a BETA dependency currently until we can ship `cyclonedx-python-lib` `4.0.0`.

**Comment by edmerrett** [comment]
@madpah thanks so much for getting to this. I will have a look 🙏🏼

**Comment by vjclions** [comment]
Hi,

Thanks!

2023 5G Challenge hosted by NTIA and DoD is requesting contestants to submit SBOM and VEX documents. When they are asked what VEX tool they recommend, they sent out VEXY link as one of the tools.

VEXY will help many companies that do not have budget to purchase those expensive SBOM and VEX tool kids.

Regards,

Vincent Chu

***@***.***

**Comment by vjclions** [comment]
Hi,

We tested the new release 4.0.0 and encountered the following issue. 

                  Vexy is configured to use 2 data sources. 
                  Parsing CycloneDX BOM for Components ----------------------------------------   0% -:--:--
                  Traceback (most recent call last):
                    File "<frozen runpy>", line 198, in _run_module_as_main
                    File "<frozen runpy>", line 88, in _run_code
                    File "D:\Program Files\Python311\Scripts\vexy.exe\__main__.py", line 7, in <module>
                    File "D:\Program Files\Python311\Lib\site-packages\vexy\client.py", line 298, in main
                      VexyCmd(args).execute()
                    File "D:\Program Files\Python311\Lib\site-packages\vexy\client.py", line 159, in execute
                      input_bom = Bom.from_json(data=json.loads(input_bom_fh.read()))  # type: ignore[attr-defined]
                                                                ^^^^^^^^^^^^^^^^^^^
                  UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 522726: illegal multibyte sequence

We traced to the following code segment and don't quite understand what "#type: ignore[attr-defined] means. 

                    input_bom: Bom
                    try:
                        with self._arguments.input_source as input_bom_fh:
                            if str(self._arguments.input_source.name).endswith('.json'):
                                input_bom = Bom.from_json(data=json.loads(input_bom_fh.read()))  # type: ignore[attr-defined]
                    
                            elif str(self._arguments.input_source.name).endswith('.xml'):
                                input_bom = Bom.from_xml(  # type: ignore[attr-defined]
                                    data=ElementTree.fromstring(input_bom_fh.read())
                                )
                    except CycloneDxException as e:
                        print(f'Failure validating input BOM: {e}')
                        return

Regards,

Vincent Chu

**Comment by leoliu-lions** [comment]
@edmerrett  I am a newbie for VEX, could you please explain your running command "cyclonedx-py -e -F | vexy -i cyclonedx.json -c VEXY_CONFIG -X"?  Many Thanks
Two questions:
1, cyclonedx-py -e -F, no options for input files
2, the first command(cyclonedx) output passed to second comand by pip, but the second command(vexy) has input option (-i)

**Comment by leoliu-lions** [comment]
@edmerrett  Okey， Got it， Thanks~
